README_EN.md

Update README_EN from README via google translate, and fix the path bug of assets photoes

docs:Update README_EN

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
app.py
image_utils.py
requests_api.py

feat: resize image to kb

---

README_EN.md
docker-compose.yml

added docker compose with updated redme in English

updated redme

---

docker-compose.yml

fix: docker-compose

---

docker-compose.yml

如果使用`Docker Compose` 就把`Gradio`和`API`服务都启动，这样不但发挥compose的优势，也可以让`README`上描述更精炼些 😄

feat: add api service into docker compose

---

app.py

Gradio增加参数：
1. 面部与照片占比
2. 头顶与照片顶部距离
3. 使用Tab来管理参数

feat: gradio advanced parameters

---

hivision/creator/layout_calculator.py

fixed 大5寸等六寸排版照镜像问题 #59

---

README.md
app.py
hivision/plugin/watermark.py

feat: watermark enhance

---

deploy_api.py

fix: creator bug

---

deploy_api.py
docs/api_CN.md
docs/api_EN.md
docs/api_JP.md
docs/api_KO.md

改进了`deploy_api.py`中fastapi接口的类型定义，以避免在SwaggerUI的调试中出现问题。
Close: #98

fix: deploy api type

---

demo/processor.py
demo/ui.py
hivision/creator/__init__.py
hivision/creator/context.py

使用缓存机制，改进了Gradio Demo在同一张照片来操作时的性能

feat: gradio performance improve

---

app.py
demo/locals.py
demo/processor.py
demo/ui.py
hivision/utils.py

1. 增加Gradio Demo - 高级参数 - DPI设置

feat: image dpi

---

demo/locals.py
demo/processor.py
demo/ui.py
hivision/creator/__init__.py
hivision/creator/context.py
hivision/plugin/beauty/base_adjust.py
hivision/plugin/beauty/handler.py

feat: add saturation

---

demo/processor.py

优化了DPI下载，可以下载设置了自定义DPI的标准照、高清照和排版照

feat: dpi download

---

demo/locales.py
demo/processor.py
demo/ui.py
hivision/creator/__init__.py
hivision/creator/context.py
hivision/creator/face_detector.py
hivision/creator/photo_adjuster.py
hivision/creator/rotation_adjust.py
hivision/creator/utils.py

feat: face alignment

---

demo/processor.py
demo/ui.py

refactor: dpi download

---

demo/ui.py
hivision/creator/__init__.py

fix: face align beauty

---

.gitignore
hivision/creator/__init__.py
hivision/creator/face_detector.py
hivision/creator/photo_adjuster.py
hivision/creator/rotation_adjust.py
rotation_adjust.py

feat: performance printing

---

README.md
app.py
hivision/creator/face_detector.py
hivision/creator/human_matting.py

feat: beast mode

---

demo/locales.py
demo/processor.py
hivision/creator/layout_calculator.py

feat: five inch

---

README.md
demo/assets/title.md
demo/processor.py
deploy_api.py
docs/api_CN.md
docs/api_EN.md

1. API接口增加美颜参数
2. 修复多人脸报错没有更新在demo上的问题

feat: api add beauty

---

README.md
README_EN.md
README_JP.md
README_KO.md

Add demo on compshare

---

demo/locales.py
demo/processor.py
hivision/creator/__init__.py
hivision/creator/context.py
hivision/creator/photo_adjuster.py

feat: horizontal_flip_option

---

demo/processor.py

fix: only kb error
